# Generated by Django 5.2.12 on 2026-04-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
