# Generated by Django 5.2.12 on 2026-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Flash Sale', max_length=200)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Informational discount percentage to show')),
                ('products', models.ManyToManyField(related_name='flash_sales', to='api.product')),
            ],
        ),
    ]
