# Generated by Django 5.2.12 on 2026-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_deposit_amount_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='target_brand',
            field=models.CharField(blank=True, help_text='If set, coupon only applies to products of this brand', max_length=200, null=True),
        ),
    ]
